{"name": "test_approve_pullrequest", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "@pytest.mark.run(order=6)\n    def test_approve_pullrequest():\n        api = Apirequests(read_base_url())\n        get_response = api.send_get(pulls, auth=auth)\n        get_pr_number = Apiresponses(get_response)\n        if get_pr_number.get_status_code() == 200:\n>           pull_request_number = get_pr_number.get_json()[0]['number']\nE           IndexError: list index out of range\n\ntest_approve_pull_request.py:24: IndexError"}, "start": 1679160952887, "stop": 1679160953209, "uuid": "f56a7910-d877-4fec-ad88-5d718039e2c6", "historyId": "7b9e1660f6ac89e6a23c546b5920e553", "testCaseId": "c2f5efca9add225954b0fd64fa3677de", "fullName": "test_approve_pull_request#test_approve_pullrequest", "labels": [{"name": "tag", "value": "run(order=6)"}, {"name": "suite", "value": "test_approve_pull_request"}, {"name": "host", "value": "AlphaTest"}, {"name": "thread", "value": "6924-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_approve_pull_request"}]}