{"name": "test_delete_pull_request", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "@pytest.mark.trylast\n    def test_delete_pull_request():\n        response = api.send_patch(pull_request, auth=auth, data=json.dumps(close_data))\n        delete_response = Apiresponses(response)\n        print(delete_response.get_status_code())\n        if (delete_response.get_status_code()) == 200:\n>           print(f\"Pull request {get_pull_request_number()} has been deleted\")\n\ntest_all_together.py:102: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    def get_pull_request_number():\n        api = Apirequests(read_base_url())\n        get_response = api.send_get(pulls, auth=auth)\n        get_pr_number = Apiresponses(get_response)\n        if get_pr_number.get_status_code() == 200:\n>           pull_request_number = get_pr_number.get_json()[0]['number']\nE           IndexError: list index out of range\n\n..\\utilities\\get_pull_request_number_helper.py:15: IndexError"}, "attachments": [{"name": "stdout", "source": "b9f6f2df-e936-46a3-953f-fe2d094fbf29-attachment.txt", "type": "text/plain"}], "start": 1679226627300, "stop": 1679226628490, "uuid": "3d897d62-81d6-4037-9028-ae2b23b4e97f", "historyId": "dd2332ab6ba08d164b2f478610a7e873", "testCaseId": "74c429202192850bed13423a0e684b8d", "fullName": "test_all_together#test_delete_pull_request", "labels": [{"name": "tag", "value": "@pytest.mark.trylast"}, {"name": "suite", "value": "test_all_together"}, {"name": "host", "value": "AlphaTest"}, {"name": "thread", "value": "16456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_all_together"}]}