{"name": "test_create_new_pr", "status": "failed", "statusDetails": {"message": "AssertionError: assert 422 == 201\n +  where 422 = <bound method Apiresponses.get_status_code of <api.api_responses.Apiresponses object at 0x0000014D5BAC3130>>()\n +    where <bound method Apiresponses.get_status_code of <api.api_responses.Apiresponses object at 0x0000014D5BAC3130>> = <api.api_responses.Apiresponses object at 0x0000014D5BAC3130>.get_status_code", "trace": "@pytest.mark.run(order=4)\n    def test_create_new_pr():\n        response = api.send_post(pulls, auth=auth, json=params)\n        pr_create_response = Apiresponses(response)\n>       assert pr_create_response.get_status_code() == 201\nE       assert 422 == 201\nE        +  where 422 = <bound method Apiresponses.get_status_code of <api.api_responses.Apiresponses object at 0x0000014D5BAC3130>>()\nE        +    where <bound method Apiresponses.get_status_code of <api.api_responses.Apiresponses object at 0x0000014D5BAC3130>> = <api.api_responses.Apiresponses object at 0x0000014D5BAC3130>.get_status_code\n\ntest_all_together.py:67: AssertionError"}, "start": 1679226625959, "stop": 1679226626338, "uuid": "44c0af05-a895-4870-bad1-fb7317d2ce02", "historyId": "41b560b1a59af6565535d677d61eb1b3", "testCaseId": "0b820b48968caf55db6ab716d7810690", "fullName": "test_all_together#test_create_new_pr", "labels": [{"name": "tag", "value": "run(order=4)"}, {"name": "suite", "value": "test_all_together"}, {"name": "host", "value": "AlphaTest"}, {"name": "thread", "value": "16456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_all_together"}]}