{"name": "test_create_new_pr", "status": "failed", "statusDetails": {"message": "AssertionError: assert 422 == 201\n +  where 422 = <bound method Apiresponses.get_status_code of <api.api_responses.Apiresponses object at 0x000002B58A645390>>()\n +    where <bound method Apiresponses.get_status_code of <api.api_responses.Apiresponses object at 0x000002B58A645390>> = <api.api_responses.Apiresponses object at 0x000002B58A645390>.get_status_code", "trace": "def test_create_new_pr():\n        api = Apirequests(read_base_url())\n        response = api.send_post(pulls, auth=auth, json=params)\n        pr_create_response = Apiresponses(response)\n>       assert pr_create_response.get_status_code() == 201\nE       assert 422 == 201\nE        +  where 422 = <bound method Apiresponses.get_status_code of <api.api_responses.Apiresponses object at 0x000002B58A645390>>()\nE        +    where <bound method Apiresponses.get_status_code of <api.api_responses.Apiresponses object at 0x000002B58A645390>> = <api.api_responses.Apiresponses object at 0x000002B58A645390>.get_status_code\n\ntest_creation_of_pullrequest.py:16: AssertionError"}, "start": 1679222801745, "stop": 1679222802176, "uuid": "e6dcf155-33aa-4f09-8395-68b183f044c2", "historyId": "c291b1acbda530a8b2583d7c04fd5449", "testCaseId": "79adebac2b71d015c39857b386ab34ec", "fullName": "test_creation_of_pullrequest#test_create_new_pr", "labels": [{"name": "suite", "value": "test_creation_of_pullrequest"}, {"name": "host", "value": "AlphaTest"}, {"name": "thread", "value": "12632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_creation_of_pullrequest"}]}